[package]
name = "vis"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
rustc-hash.workspace = true
hz-config = {path = "../config"}
hz-mesh = {path = "../ccmesh"}
