[package]
name = "hz-workload"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
zipf.workspace = true
rustc-hash.workspace = true
hz-config = { path = "../config" }