disallowed-types = [
    "std::collections::HashMap",
    "std::collections::HashSet",
# futex based mutex has been merged in rust 1.62
# https://blog.rust-lang.org/2022/06/30/Rust-1.62.0.html
#    "std::sync::Mutex",
#    "std::sync::RwLock",
]
